# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$HOME/Projects/pconfig/local/bin:$HOME/local/bin:$HOME/bin:$PATH

export PATH

export LD_LIBRARY_PATH="$HOME/Projects/pconfig/local/lib"
