# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs

export JAVA_HOME=`/usr/libexec/java_home -v 1.7`

PATH=$HOME/Projects/pconfig/local/bin:$HOME/local/bin:$HOME/bin:$PATH:$JAVA_HOME/bin

export PATH

export LD_LIBRARY_PATH="$HOME/Projects/pconfig/local/lib"
